api/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^update_state/([0-9]+)/$', views.update_state, name='update_state'),
    url(r'^fetch_state/([0-9]+)/$', views.fetch_state, name='fetch_state'),
    url(
        r'^update_channel/([0-9]+)/$',
        views.update_channel,
        name='update_channel'),
    url(r'^add_message/([0-9]+)/$', views.add_message, name='add_message'),
    url(r'^view_files/([0-9]+)/$', views.view_files, name='view_files')
]

collabide/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^api/', include('api.urls')),
    url(r'', include('ide.urls')),
    url(r'^admin/', admin.site.urls),
]

ide/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.default, name='default'),
    url(r'^guestpage/$', views.guestpage, name='guestpage'),
    url(r'^login/$', views.login, name='login'),
    url(r'^signup/$', views.signup, name='signup'),
    url(r'^welcome/$', views.welcome, name='welcome'),
    url(r'^([0-9]+)/$', views.index, name='index'),
    url(r'new_project/$', views.new_project, name='new_project'),
    url(r'^join_project/$', views.join_project, name='join_project'),
    url(r'^logout/$', views.logout, name='logout'),
    url(r'^dashboard/$', views.dashboard, name='dashboard'),
    url(r'^new_channel/([0-9]+)/$', views.new_channel, name='new_channel')
]

ide/models.py
from django.db import models


class SiteUser(models.Model):
    username = models.CharField(max_length=30, unique=True)
    email = models.CharField(max_length=50, unique=True)
    password = models.CharField(max_length=30)
    name = models.CharField(max_length=40)

    def __str__(self):
        return self.username


class Project(models.Model):
    users = models.ManyToManyField(SiteUser)
    name = models.CharField(max_length=40, unique=True)
    admin = models.ForeignKey(SiteUser, related_name='admins')
    token = models.CharField(max_length=70)

    def __str__(self):
        return self.name + ', ' + self.admin.name

    # def save(
    #       self, force_insert=False, force_update=False,
    #        using=None, first_time=False):
    #   if not first_time:
    #        self.users.add(self)
    #   super().save()

    def get_users_names(self):
        for user in self.users.all():
            yield user.name

    def get_channels(self):
        channels = self.channels.all()
        return channels

'''
class Repo(models.Model):
    project = models.ForeignKey(Project, related_name='repos')
    language = models.IntegerField()   # 1: python, 2: c, 3: javascript

    def __str__(self):
        return self.project.name
'''

class Commit(models.Model):
    project = models.ForeignKey(Project, null=True)
    commited_on = models.DateTimeField()
    commited_by = models.ForeignKey(SiteUser)
    state = models.BinaryField()

    def __str__(self):
        return str(self.commited_on) + ' ' + self.commited_by.username


class DiscussionChannel(models.Model):
    project = models.ForeignKey(Project, related_name='channels')
    name = models.CharField(max_length=8)
    members = models.ManyToManyField(SiteUser)
    for_all_members = models.BooleanField(default=False)

    def __str__(self):
        return self.name + ', ' + self.project.name


class DiscussionMessage(models.Model):
    channel = models.ForeignKey(
        DiscussionChannel, related_name='discussion_message_set')
    sender = models.ForeignKey(SiteUser)
    content = models.TextField()
    time = models.DateTimeField()

    def __str__(self):
        return self.content[:30] + '...'

    def save(self, *args, **kwargs):
        self.format_message()
        super().save(*args, **kwargs)

    def format_message(self):
        self.content = self.content.strip()
        self.content = self.content.replace('\n', '<br />')

ide/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import SiteUser, Project, DiscussionChannel
from .utils import is_logged_in, setup_project


def guestpage(request):
    return render(request, 'ide/guestpage.html')


def login(request):
    member = SiteUser.objects.filter(
        email=request.POST['email'],
        password=request.POST['password']
    )
    if not member:
        return HttpResponse('Invalid username or password')
    member = member[0]
    request.session['m_id'] = member.id
    return redirect('/welcome/')


def signup(request):
    if SiteUser.objects.filter(email=request.POST['email']).exists():
        return HttpResponse('Email already exists')
    if SiteUser.objects.filter(username=request.POST['username']).exists():
        return HttpResponse('Username already exists')
    member = SiteUser.objects.create(
        name=request.POST['name'],
        email=request.POST['email'],
        username=request.POST['username'],
        password=request.POST['password']
    )
    request.session['m_id'] = member.id
    return redirect('/welcome/')


@is_logged_in
def welcome(member, request):
    return render(request, 'ide/welcome.html', context={'member': member})


@is_logged_in
def index(member, request, project_id):
    project = Project.objects.filter(pk=project_id)
    if not project:
        return HttpResponse('The given project does not exist')
    project = project[0]
    if not project.users.filter(id=member.id).exists() and \
            project.admin != member:
        return HttpResponse('You are not authorized to work on this project.')
    context = {}
    context['member'] = member
    context['project'] = project
    context['channel_set'] = project.channels.filter(members__id=member.id)
    return render(request, 'ide/index.html', context)


def default(request):
    m_id = request.session.get('m_id', False)
    if not m_id:
        return redirect('/guestpage/')
    return redirect('/welcome/')


@is_logged_in
def new_project(member, request):
    project_name = request.POST['name']
    if Project.objects.filter(name=project_name).exists():
        return HttpResponse(
            'Project with the same name already exists. Try a different name.')
    project = Project.objects.create(
        name=project_name,
        admin=member,
        token=request.POST['token']
    )
    members = request.POST.get('project_members', False)
    if members:
        members = members.split(';')
    else:
        members = []
    membs = []
    for memb in members:
        username = memb.strip()
        if SiteUser.objects.filter(username=username):
            if member.username == username:
                continue
            membs.append(SiteUser.objects.get(username=username))
        else:
            return HttpResponse('The given user does not exist')
    if membs:
        project.users.add(*membs)
    # project.users.add(member)
    project.save()
    setup_project(project)
    return redirect('/%d/' % project.id)


@is_logged_in
def join_project(member, request):
    project = Project.objects.filter(name=request.POST['name'])
    if not project:
        return HttpResponse('Project with the given name doesn\'t exist')
    project = project[0]
    if not project.token == request.POST['token']:
        return HttpResponse('Invalid token given for the project')
    project.users.add(member)
    channels = project.channels.filter(for_all_members=True)
    for channel in channels:
        channel.members.add(member)
    project.save()
    return redirect('/%d/' % project.id)


def logout(request):
    if request.session.get('m_id', False):
        del request.session['m_id']
    return redirect('/guestpage/')


@is_logged_in
def dashboard(member, request):
    if request.method == 'GET':
        return render(request, 'ide/dashboard.html', {'member': member})
    return HttpResponse('Notthing happens right now! :p')


@is_logged_in
def new_channel(member, request, project_id):
    if request.method == 'GET':
        project = Project.objects.filter(pk=project_id)
        if not project:
            return HttpResponse('Project does not exist')
        project = project[0]
        return render(request, 'ide/new_channel.html', {'project': project})
    project = Project.objects.filter(pk=project_id)
    if not project:
        return HttpResponse('Project does not exist')
    project = project[0]
    names = request.POST['channel_members'].split(';')
    channel = DiscussionChannel.objects.create(
        project=project,
        name=request.POST['channel_name']
    )
    try:
        channel.members.add(member)
        channel.members.add(*[
            SiteUser.objects.get(username=name.strip()) for name in names
        ])
        channel.save()
    except Exception:
        return HttpResponse('Invalid usernames given')
    return redirect('/%s/' % project_id)

ide/templates/ide/base_form_display.html
<!DOCTYPE html>
<html>
<head>
    <title>{% block title%}{% endblock %}</title>
    <style type="text/css">
    .bg {
            //background-image: url('/static/monet.jpg');
            height: 100%;
            background-position: center;
            background-repeat: repeat-y;
            background-size: cover;
        }
        input {
            width: 75%;
            padding: 12px 20px;
            margin: 8px 0;
            box-sizing: border-box;
            border: 2px solid green;
            border-radius: 4px;
        }
        input[type=submit] {
            width: 50%;
            cursor: pointer;
        }
        {% block form_style %}
        .generic_form {
            position: relative;
            margin-top: 50px;
            margin-left: auto;
            margin-right: auto;
            margin-bottom: 30px;
            width: 400px;
            padding: 20px;
            background-color: white;

        }
        {% endblock %}
        .user_menu a {
            display: block;
            float: right;
            text-decoration: none;
            color: white;
            width: auto;
            padding: 10px;
            background-color: green;
            border: 2px inset white;
            border-radius: 8px;
        }
    {% block style %}{% endblock %}
    </style>
</head>
<body class="bg">
    {% block user_menu %}
    <div class="user_menu">
        <a href="/logout/">Log Out</a>
        {% block dashboard %}{% endblock %}
    </div>
    {% endblock %}
    {% block pre_form %}{% endblock %}
    <div class="generic_form">
        {% block generic_form %}{% endblock %}
    </div>
    {% block post_form %}{% endblock %}
</body>
</html>

ide/templates/ide/dashboard.html
{% extends "ide/base_form_display.html" %}
{% block title %}Collaborative IDE | Dashboard{% endblock %}
{% block style %}
.stats {
    width: 30%;
    float: left;
    border: 2px solid blue;
}
{% endblock %}
{% block form_style %}
.generic_form {
            //position: relative;
            margin-top: 10px;
            margin-left: 10px;
            float: left;
            //margin-bottom: 30px;
            width: 30%;
            padding: 20px;
            background-color: white;
            border: 2px solid black;

        }
{% endblock %}
{% block pre_form %}
<div class="stats">
    <h3>Projects where serving as Admin</h3>
    <ul>
        {% for proj in member.admins.all %}
        <li>Project Name: {{ proj.name }} <br />
            Token: {{ proj.token }} <br />
            Contributors: <br />
            <ul>{% for contrib in proj.users.all %}
                <li>{{ contrib.name }}</li>
                {% endfor %}
            </ul>
        </li>
        {% endfor %}
    </ul>
    <h3>Other Projects Contributing in</h3>
    <ul>
        {% for proj in member.project_set.all %}
        <li>Project Name: {{ proj.name }}<br />
            Admin: {{ proj.admin.name }}<br />
            Contributors: <br />
            <ul>
                {% for contrib in proj.get_users_names %}
                <li>
                    {{ contrib }}
                </li>
                {% endfor %}
            </ul>
        </li>
        {% endfor %}
    </ul>
</div>
{% endblock %}
{% block dashboard %}<a href="/">Home</a>{% endblock %}
{% block generic_form %}
<form action="/dashboard/" method="POST"> {% csrf_token %}
    <input type="password" name="pr_password" placeholder="Enter current password"><br />
    <input type="password" name="password" placeholder="Change login password"><br />
    <input type="password" name="password2" placeholder="Confirm password"><br />
    <input type="text" name="name" placeholder="Change name"><br />
    <input type="text" name="token" placeholder="Change tokens"><br />
    <textarea name="remove_member" placeholder="Remove members"></textarea><br />
    <input type="submit" value="Update">
</form>
{% endblock %}

ide/templates/ide/guestpage.html
{% extends "ide/base_form_display.html" %}
{% block title %}Collaborative IDE: Log In or Sign Up{% endblock %}
{% block user_menu %}{% endblock %}
{% block generic_form %}
<h2>Log In</h2>
            <form action="/login/" method="POST">
                {% csrf_token %}
                <input type="email" name="email" placeholder="Email address" required />
                <br />
                <input type="password" name="password" placeholder="Enter password" required />
                <br />
                <input type="submit" value="Log In">
            </form>
            <br />
            <h2>Sign Up</h2>
            <form action="/signup/" method="POST">
                {% csrf_token %}
                <input type="text" name="name" placeholder="Enter your name" required />
                <input type="email" name="email" placeholder="Enter your email" required />
                <br />
                <input type="text" name="username" placeholder="Enter a username" required />
                <br />
                <input type="password" name="password" placeholder="Enter a password" required />
                <br />
                <input type="submit" value="Sign Up">
            </form>
{% endblock %}

ide/templates/ide/guestpage_old_copy.html
<html>
    <head>
        <title>Lambsteak Lab: Log In</title>
        <style>
        .bg {
            //background-image: url('/static/monet.jpg');
            height: 100%;
            background-position: center;
            background-repeat: repeat-y;
            background-size: cover;
        }
        input {
            width: 75%;
            padding: 12px 20px;
            margin: 8px 0;
            box-sizing: border-box;
            border: 2px solid green;
            border-radius: 4px;
        }
        input[type=submit] {
            width: 50%;
        }

        #guest_form {
            position: relative;
            margin-top: 50px;
            margin-left: auto;
            margin-right: auto;
            margin-bottom: 30px;
            width: 400px;
            padding: 20px;
            background-color: white;

        }
        </style>
    </head>
    <body class='bg'>
        <div id="guest_form">
            <h2>Log In</h2>
            <form action="/login/" method="POST">
                {% csrf_token %}
                <input type="email" name="email" placeholder="Email address" required />
                <br />
                <input type="password" name="password" placeholder="Enter password" required />
                <br />
                <input type="submit" value="Log In" style="cursor: pointer;">
            </form>
            <br />
            <h2>Sign Up</h2>
            <form action="/signup/" method="POST">
                {% csrf_token %}
                <input type="text" name="name" placeholder="Enter your name" required />
                <input type="email" name="email" placeholder="Enter your email" required />
                <br />
                <input type="text" name="username" placeholder="Enter a username" required />
                <br />
                <input type="password" name="password" placeholder="Enter a password" required />
                <br />
                <input type="submit" value="Sign Up" style="cursor: pointer;">
            </form>
        </div>
    </body>
</html>

ide/templates/ide/new_channel.html
{% extends "ide/base_form_display.html" %}
{% block title %}Collaborative IDE | Add New Channel{% endblock %}
{% block dashboard %}<a href="/">Home</a> <a href="/dashboard/">Dashboard</a>{% endblock %}
{% block generic_form %}
    <form action="/new_channel/{{ project.id }}/" method="POST">
        {% csrf_token %}
        <h2>Add New Channel in Project: {{ project.name }}</h2>
        <input type="text" name="channel_name" placeholder="Enter channel name" maxlength="8" required /><br />
        <input type="text" name="channel_members" placeholder="Enter channel members" maxlength="200" required /><br />
        <input type="submit" value="Create Channel">
    </form>
{% endblock %}

ide/templates/ide/welcome.html
{% extends "ide/base_form_display.html" %}
    {% block title %}Collaborative IDE: Welcome {{ member.name }}{% endblock %}
{% block generic_form %}
    <form method="POST" action="/new_project/">
        {% csrf_token %}
        <h1>Start A Project</h1>
        <input type="text" name="name" placeholder="Project Name" required /><br />
        <textarea name="project_members" placeholder="Enter project members separated by semicolons" /></textarea><br />
        <input type="text" name="token" placeholder="Enter authorization token" required /><br />
        <input type="submit" value="Create">
    </form>
    <br /><br />
    <form action="/join_project/" method="POST">
        {% csrf_token %}
        <h1>Join A Project</h1>
        <input type="text" name="name" placeholder="Enter project name" required /><br />
        <input type="text" name="token" placeholder="Enter project token" required /> <br />
        <input type="submit" value="Join">
    </form>
{% endblock %}
{% block dashboard %}<a href="/dashboard/">Dashboard</a>{% endblock %}